<x-admin-layout>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iusto, itaque voluptas unde officia cum quo omnis, est expedita repellendus ea dolorem numquam, non illo? Quia sint architecto impedit provident maxime.</p>
    <p>Placeat voluptas minima, id aspernatur dignissimos illo iure accusantium soluta recusandae dolores vero inventore molestiae impedit possimus pariatur animi odit rerum magni eius. Dolorem rem eveniet est cumque! Reiciendis, magni.</p>
    <p>Inventore, harum dicta! Libero at corporis tempora deleniti fugit in pariatur neque expedita, non, ea fugiat officiis nihil eius est, eos temporibus adipisci laborum. Maxime atque fuga soluta natus pariatur!</p>
    <p>Numquam, odit ratione nostrum quaerat excepturi voluptatibus nesciunt iusto. Ducimus id facere officiis amet recusandae culpa perferendis dolore, eius sunt, consequuntur quos, necessitatibus provident ad in quasi aliquid veniam a!</p>
    <p>Eaque suscipit vero, quisquam ipsum eos debitis a eligendi tempora libero veniam nisi nobis qui ullam dolorum odit perspiciatis hic voluptatum distinctio architecto accusantium. Enim accusantium consectetur molestiae ea quidem.</p>
    <p>Voluptates quo doloribus, accusamus sed animi eaque earum! Consequatur voluptate harum ipsa nostrum porro est, reprehenderit, nisi animi voluptates enim eum adipisci. Atque quasi praesentium consequatur magni nesciunt architecto dolores.</p>
    <p>Distinctio temporibus accusamus error odio voluptatem. Perspiciatis facere consectetur est eligendi. Necessitatibus sequi ipsum voluptatem quidem aspernatur maxime saepe tenetur iure quas odio! Harum incidunt amet adipisci possimus numquam eum?</p>
    <p>Eius, sequi. Harum delectus tempora voluptatum saepe minus sit numquam a accusamus. Eaque praesentium rerum quae eveniet possimus doloribus, aperiam quidem exercitationem quisquam laudantium saepe magni ad molestias distinctio temporibus.</p>
    <p>Reiciendis tempore earum incidunt beatae est nemo distinctio recusandae soluta minus, qui nulla animi laborum odit quo! Minus cumque totam esse ducimus quis fugiat? Alias consequuntur reprehenderit dignissimos quas maxime?</p>
    <p>Possimus maiores eligendi assumenda est temporibus deserunt nostrum animi quod iure culpa. Et, aliquid. Sunt neque quis fuga culpa cupiditate laborum omnis quas a quaerat explicabo, vero officia et ut!</p>
    <p>Labore cupiditate ducimus illo tempore quidem harum adipisci perspiciatis at blanditiis, possimus sed corporis doloribus quas eaque ipsum reiciendis dignissimos omnis voluptatem qui odit esse? Voluptatem praesentium reiciendis quas voluptate!</p>
    <p>Amet eligendi facere quam, dignissimos ratione fugit nulla itaque corrupti quidem doloribus autem non commodi! Minima ex facere excepturi magnam recusandae officiis sint. Dolore autem impedit doloribus vel iure consequuntur.</p>
    <p>Iure illo assumenda velit laudantium quisquam perferendis, eligendi optio minus commodi. Corrupti ipsa dolores ea nam harum, nulla voluptatum temporibus eveniet neque suscipit dolorem optio earum veniam ut distinctio laboriosam!</p>
    <p>Earum, repellat consequuntur, et commodi aliquid culpa aperiam eveniet rem aliquam vero reiciendis, ut sit fugit eaque esse deleniti veritatis nemo? Ut non animi ducimus, illum ratione sunt tempora nemo.</p>
    <p>Ut numquam nihil distinctio error blanditiis tempore quas corporis natus repudiandae. Magni ea, sapiente qui recusandae earum ratione natus nobis dolores aperiam obcaecati. Eius magni incidunt, vel iure soluta assumenda.</p>
    <p>Deleniti molestias pariatur quibusdam saepe, molestiae praesentium recusandae qui eaque repellat cumque dicta doloremque voluptas? Sapiente ullam quia inventore excepturi eius nisi ducimus omnis consequuntur, minima mollitia officia, cumque fugit.</p>
    <p>Inventore expedita quo, natus neque iusto at praesentium eligendi obcaecati reprehenderit exercitationem, culpa tempore rem nobis similique laborum officia rerum laboriosam id nam quae debitis nemo! Placeat repellat fugit quibusdam.</p>
    <p>Porro totam magni a sapiente molestias illo quas incidunt consequatur eveniet, accusamus quia eius natus nam reiciendis sint distinctio, esse veritatis nobis, fugit quis tempore ut provident. Molestiae, laborum libero!</p>
    <p>Culpa quas quam tenetur odit harum ullam sapiente omnis aliquid veniam possimus incidunt, commodi, reprehenderit quia fugiat eum ea adipisci recusandae optio praesentium nemo assumenda voluptatum ipsam inventore fugit? Ex!</p>
    <p>Nemo possimus ratione tenetur nihil, cum ut tempora temporibus, minus atque consectetur deserunt consequuntur nostrum facilis consequatur fuga dicta omnis praesentium? Corporis itaque veniam aut dolores ullam maxime, cum consectetur?</p>
</x-admin-layout>
